### PR TITLE
Add API endpoint to verify address

### PR DESCRIPTION
**Pull request by JamesMGreene**
### Why?

Towards #36

### What Changed?

- Refined the existing Lob Templates API usage to use `await` for Promises
  - Added alternative endpoint `GET /api/lob/templates/:templateId` to `GET /api/lob/:templateId` to avoid vagueness
  - The old endpoint should be removed once the [frontend code using it](https://github.com/Ally-Guide/amplify-front-end/blob/7d22a6c0ff819f1a3e6794a886339ee11aca1b80/src/components/SearchReps.vue#L89-L91) can be updated
- Added a new API endpoint `POST /api/lob/addressVerification` for verifying US addresses via the Lob API
  - Also considers addresses that are non-residential, P.O. Boxes, or in Puerto Rico to be invalid. Are those all correct assumptions? Any other invalidating reasons to add? 🤔 cc @manishapriya94 

#### TODO

- [x] Update `.env.example` **and** contribution guide for `LOB_API_KEY`
- [x] Add integration tests?
- [x] Update [frontend code for retrieving a template](https://github.com/Ally-Guide/amplify-front-end/blob/7d22a6c0ff819f1a3e6794a886339ee11aca1b80/src/components/SearchReps.vue#L89-L91) to use the updated URL
  - https://github.com/Ally-Guide/amplify-front-end/pull/38
  - https://github.com/Ally-Guide/amplify-front-end/pull/39

### CODE REVIEW

**Comment by mahrsbar** [comment]
@JamesMGreene Are you able to update the [API wik](https://github.com/Ally-Guide/amplify-back-end/wiki) inside the pages so I can be certain I'm using the correct link?

**Comment by manishapriya94** [comment]
Hi @JamesMGreene those assumptions are correct as it has to be the registered address following rules of voter registration! 

@BeeXiong could you help clarify which URL is correct for the LOB API Key?

**Review by BeeXiong — APPROVED** [review]
Looks Good to me.

**Comment by BeeXiong** [comment]
@mahrsbar The [wiki](https://github.com/Ally-Guide/amplify-back-end/wiki/Lob-Endpoints) was updated previously and reflects the correct URL `api/lob/templates/{templateId}`. 

Also added the `POST` for address` verification `api/lob/addressverification}`. Need to regroup with @JamesMGreene to better document but it's there for now.

**Pull request merged**
