### PR TITLE
Lob API Authentication Question

### PR DESCRIPTION
**Pull request by BeeXiong**
❓ about how to implement Lob API with secret.

Docs say the `lob` library doesn't support retrieval of templates at this point.

image

Using Axios to make the call instead. Didn't know where the secret should be placed however. Currently have it listed "params" but unsure if that's where it should be in the request.

Any suggestions?

### CODE REVIEW

**Review by BeeXiong — COMMENTED** [review]
This is where I'm confused and unsure of where to put the secret in the request

**Comment by manishapriya94** [comment]
Oops, I think for retrieve we want to use letter template

?

**Comment by teakopp** [comment]
@BeeXiong I was able to get the example working with the code below with the test API key from the docs
```
const axios = require("axios");

const config = {
  method: "get",
  url: "https://api.lob.com/v1/templates/tmpl_c94e83ca2cd5121",
  headers: {
    Authorization:
      "Basic dGVzdF8wZGM4ZDUxZTBhY2ZmY2IxODgwZTBmMTljNzliMmY1YjBjYzo6",
  },
};

getData
axios(config)
  .then(function (response) {
    console.log(JSON.stringify(response.data));
  })
  .catch(function (error) {
    console.log(error);
  });
```

Here's an async example
```
const axios = require("axios");

async function getData() {
  const config = {
    method: "get",
    url: "https://api.lob.com/v1/templates/tmpl_c94e83ca2cd5121",
    headers: {
      Authorization:
        "Basic dGVzdF8wZGM4ZDUxZTBhY2ZmY2IxODgwZTBmMTljNzliMmY1YjBjYzo6",
    },
  };

  const res = await axios(config);
  console.log(JSON.stringify(res.data));
}

getData();

```

**Comment by BeeXiong** [comment]
@teakopp I just got it working too slightly different.

Screen Shot 2021-05-25 at 11 10 54 PM

Looks like it was a config issue + Lob naming convention
                            ⬇️ ⬇️ 


Screen Shot 2021-05-25 at 11 13 27 PM

              

Screen Shot 2021-05-25 at 11 07 47 PM

**Pull request closed without merging**
